//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TXTextControl.Words.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TXTextControl.Words.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Add Comment....
        /// </summary>
        public static string Item_Edit_Comments_AddComment_Text {
            get {
                return ResourceManager.GetString("Item_Edit_Comments_AddComment_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Review Comments....
        /// </summary>
        public static string Item_Edit_Comments_ReviewComments_Text {
            get {
                return ResourceManager.GetString("Item_Edit_Comments_ReviewComments_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Co_mments.
        /// </summary>
        public static string Item_Edit_Comments_Text {
            get {
                return ResourceManager.GetString("Item_Edit_Comments_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Copy.
        /// </summary>
        public static string Item_Edit_Copy_Text {
            get {
                return ResourceManager.GetString("Item_Edit_Copy_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cu_t.
        /// </summary>
        public static string Item_Edit_Cut_Text {
            get {
                return ResourceManager.GetString("Item_Edit_Cut_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _For {0}.
        /// </summary>
        public static string Item_Edit_EditableRegions_Add_ForCurrentUser_Text {
            get {
                return ResourceManager.GetString("Item_Edit_EditableRegions_Add_ForCurrentUser_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For _Everyone.
        /// </summary>
        public static string Item_Edit_EditableRegions_Add_ForEveryone_Text {
            get {
                return ResourceManager.GetString("Item_Edit_EditableRegions_Add_ForEveryone_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Add.
        /// </summary>
        public static string Item_Edit_EditableRegions_Add_Text {
            get {
                return ResourceManager.GetString("Item_Edit_EditableRegions_Add_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _For {0}.
        /// </summary>
        public static string Item_Edit_EditableRegions_Remove_ForCurrentUser_Text {
            get {
                return ResourceManager.GetString("Item_Edit_EditableRegions_Remove_ForCurrentUser_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For _Everyone.
        /// </summary>
        public static string Item_Edit_EditableRegions_Remove_ForEveryone_Text {
            get {
                return ResourceManager.GetString("Item_Edit_EditableRegions_Remove_ForEveryone_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Remove.
        /// </summary>
        public static string Item_Edit_EditableRegions_Remove_Text {
            get {
                return ResourceManager.GetString("Item_Edit_EditableRegions_Remove_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Editable Regions.
        /// </summary>
        public static string Item_Edit_EditableRegions_Text {
            get {
                return ResourceManager.GetString("Item_Edit_EditableRegions_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Find....
        /// </summary>
        public static string Item_Edit_Find_Text {
            get {
                return ResourceManager.GetString("Item_Edit_Find_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Paste.
        /// </summary>
        public static string Item_Edit_Paste_Text {
            get {
                return ResourceManager.GetString("Item_Edit_Paste_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow _Copy.
        /// </summary>
        public static string Item_Edit_Permissions_AllowCopy_Text {
            get {
                return ResourceManager.GetString("Item_Edit_Permissions_AllowCopy_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow _Editing Form Fields.
        /// </summary>
        public static string Item_Edit_Permissions_AllowEditingFormFields_Text {
            get {
                return ResourceManager.GetString("Item_Edit_Permissions_AllowEditingFormFields_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow _Formatting.
        /// </summary>
        public static string Item_Edit_Permissions_AllowFormatting_Text {
            get {
                return ResourceManager.GetString("Item_Edit_Permissions_AllowFormatting_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Formatting _Styles.
        /// </summary>
        public static string Item_Edit_Permissions_AllowFormattingStyles_Text {
            get {
                return ResourceManager.GetString("Item_Edit_Permissions_AllowFormattingStyles_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow _Printing.
        /// </summary>
        public static string Item_Edit_Permissions_AllowPrinting_Text {
            get {
                return ResourceManager.GetString("Item_Edit_Permissions_AllowPrinting_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Read Only.
        /// </summary>
        public static string Item_Edit_Permissions_ReadOnly_Text {
            get {
                return ResourceManager.GetString("Item_Edit_Permissions_ReadOnly_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permi_ssions.
        /// </summary>
        public static string Item_Edit_Permissions_Text {
            get {
                return ResourceManager.GetString("Item_Edit_Permissions_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pr_otect Document.
        /// </summary>
        public static string Item_Edit_ProtectDocument_Text {
            get {
                return ResourceManager.GetString("Item_Edit_ProtectDocument_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Redo.
        /// </summary>
        public static string Item_Edit_Redo_Text {
            get {
                return ResourceManager.GetString("Item_Edit_Redo_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rep_lace....
        /// </summary>
        public static string Item_Edit_Replace_Text {
            get {
                return ResourceManager.GetString("Item_Edit_Replace_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select _All.
        /// </summary>
        public static string Item_Edit_SelectAll_Text {
            get {
                return ResourceManager.GetString("Item_Edit_SelectAll_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        public static string Item_Edit_Text {
            get {
                return ResourceManager.GetString("Item_Edit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Review Tracked Changes....
        /// </summary>
        public static string Item_Edit_TrackedChanges_ReviewTrackedChanges_Text {
            get {
                return ResourceManager.GetString("Item_Edit_TrackedChanges_ReviewTrackedChanges_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trac_ked Changes.
        /// </summary>
        public static string Item_Edit_TrackedChanges_Text {
            get {
                return ResourceManager.GetString("Item_Edit_TrackedChanges_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Track Changes.
        /// </summary>
        public static string Item_Edit_TrackedChanges_TrackChanges_Text {
            get {
                return ResourceManager.GetString("Item_Edit_TrackedChanges_TrackChanges_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Undo.
        /// </summary>
        public static string Item_Edit_Undo_Text {
            get {
                return ResourceManager.GetString("Item_Edit_Undo_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Account Settings....
        /// </summary>
        public static string Item_File_CurrentUser_AccountSettings_Text {
            get {
                return ResourceManager.GetString("Item_File_CurrentUser_AccountSettings_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign _Out.
        /// </summary>
        public static string Item_File_CurrentUser_SignOut_Text {
            get {
                return ResourceManager.GetString("Item_File_CurrentUser_SignOut_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string Item_File_CurrentUser_Text {
            get {
                return ResourceManager.GetString("Item_File_CurrentUser_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string Item_File_Exit_Text {
            get {
                return ResourceManager.GetString("Item_File_Exit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New.
        /// </summary>
        public static string Item_File_New_Text {
            get {
                return ResourceManager.GetString("Item_File_New_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open….
        /// </summary>
        public static string Item_File_Open_Text {
            get {
                return ResourceManager.GetString("Item_File_Open_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Se_tup….
        /// </summary>
        public static string Item_File_PageSetup_Text {
            get {
                return ResourceManager.GetString("Item_File_PageSetup_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Print....
        /// </summary>
        public static string Item_File_Print_Text {
            get {
                return ResourceManager.GetString("Item_File_Print_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print _Quick.
        /// </summary>
        public static string Item_File_PrintQuick_Text {
            get {
                return ResourceManager.GetString("Item_File_PrintQuick_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Recent Files.
        /// </summary>
        public static string Item_File_RecentFiles_Text {
            get {
                return ResourceManager.GetString("Item_File_RecentFiles_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        public static string Item_File_Save_Text {
            get {
                return ResourceManager.GetString("Item_File_Save_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save _As….
        /// </summary>
        public static string Item_File_SaveAs_Text {
            get {
                return ResourceManager.GetString("Item_File_SaveAs_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign _In....
        /// </summary>
        public static string Item_File_SignIn_Text {
            get {
                return ResourceManager.GetString("Item_File_SignIn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string Item_File_Text {
            get {
                return ResourceManager.GetString("Item_File_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Barcode....
        /// </summary>
        public static string Item_Format_Barcode_Text {
            get {
                return ResourceManager.GetString("Item_Format_Barcode_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boo_kmark....
        /// </summary>
        public static string Item_Format_Bookmark_Text {
            get {
                return ResourceManager.GetString("Item_Format_Bookmark_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _1, 2, 3.
        /// </summary>
        public static string Item_Format_BulletsAndNumbering_ArabicNumbers_Text {
            get {
                return ResourceManager.GetString("Item_Format_BulletsAndNumbering_ArabicNumbers_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As Structured _List.
        /// </summary>
        public static string Item_Format_BulletsAndNumbering_AsStructuredList_Text {
            get {
                return ResourceManager.GetString("Item_Format_BulletsAndNumbering_AsStructuredList_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B_ullets.
        /// </summary>
        public static string Item_Format_BulletsAndNumbering_Bullets_Text {
            get {
                return ResourceManager.GetString("Item_Format_BulletsAndNumbering_Bullets_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _A, B, C.
        /// </summary>
        public static string Item_Format_BulletsAndNumbering_CapitalLetters_Text {
            get {
                return ResourceManager.GetString("Item_Format_BulletsAndNumbering_CapitalLetters_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Decrease Level.
        /// </summary>
        public static string Item_Format_BulletsAndNumbering_DecreaseLevel_Text {
            get {
                return ResourceManager.GetString("Item_Format_BulletsAndNumbering_DecreaseLevel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_ncrease Level.
        /// </summary>
        public static string Item_Format_BulletsAndNumbering_IncreaseLevel_Text {
            get {
                return ResourceManager.GetString("Item_Format_BulletsAndNumbering_IncreaseLevel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a, _b, c.
        /// </summary>
        public static string Item_Format_BulletsAndNumbering_Letters_Text {
            get {
                return ResourceManager.GetString("Item_Format_BulletsAndNumbering_Letters_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Properties....
        /// </summary>
        public static string Item_Format_BulletsAndNumbering_Properties_Text {
            get {
                return ResourceManager.GetString("Item_Format_BulletsAndNumbering_Properties_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _I, II, III, IV.
        /// </summary>
        public static string Item_Format_BulletsAndNumbering_RomanNumbers_Text {
            get {
                return ResourceManager.GetString("Item_Format_BulletsAndNumbering_RomanNumbers_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to i, ii, iii, i_v.
        /// </summary>
        public static string Item_Format_BulletsAndNumbering_SmallRomanNumbers_Text {
            get {
                return ResourceManager.GetString("Item_Format_BulletsAndNumbering_SmallRomanNumbers_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bullets and _Numbering.
        /// </summary>
        public static string Item_Format_BulletsAndNumbering_Text {
            get {
                return ResourceManager.GetString("Item_Format_BulletsAndNumbering_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Character....
        /// </summary>
        public static string Item_Format_Character_Text {
            get {
                return ResourceManager.GetString("Item_Format_Character_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colu_mns....
        /// </summary>
        public static string Item_Format_Columns_Text {
            get {
                return ResourceManager.GetString("Item_Format_Columns_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit....
        /// </summary>
        public static string Item_Format_FormFields_Edit_Text {
            get {
                return ResourceManager.GetString("Item_Format_FormFields_Edit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Form _Validation.
        /// </summary>
        public static string Item_Format_FormFields_EnableFormValidation_Text {
            get {
                return ResourceManager.GetString("Item_Format_FormFields_EnableFormValidation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Manage Conditional Instructions....
        /// </summary>
        public static string Item_Format_FormFields_ManageConditionalInstructions_Text {
            get {
                return ResourceManager.GetString("Item_Format_FormFields_ManageConditionalInstructions_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Form Fields.
        /// </summary>
        public static string Item_Format_FormFields_Text {
            get {
                return ResourceManager.GetString("Item_Format_FormFields_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Headers and Footers....
        /// </summary>
        public static string Item_Format_HeadersAndFooters_Text {
            get {
                return ResourceManager.GetString("Item_Format_HeadersAndFooters_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hype_rlink....
        /// </summary>
        public static string Item_Format_Hyperlink_Text {
            get {
                return ResourceManager.GetString("Item_Format_Hyperlink_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Image....
        /// </summary>
        public static string Item_Format_Image_Text {
            get {
                return ResourceManager.GetString("Item_Format_Image_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Language....
        /// </summary>
        public static string Item_Format_Language_Text {
            get {
                return ResourceManager.GetString("Item_Format_Language_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Bor_ders....
        /// </summary>
        public static string Item_Format_PageBorders_Text {
            get {
                return ResourceManager.GetString("Item_Format_PageBorders_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page C_olor....
        /// </summary>
        public static string Item_Format_PageColor_Text {
            get {
                return ResourceManager.GetString("Item_Format_PageColor_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page N_umber....
        /// </summary>
        public static string Item_Format_PageNumberField_Text {
            get {
                return ResourceManager.GetString("Item_Format_PageNumberField_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Paragraph....
        /// </summary>
        public static string Item_Format_Paragraph_Text {
            get {
                return ResourceManager.GetString("Item_Format_Paragraph_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Body Text.
        /// </summary>
        public static string Item_Format_ParagraphStructureLevels_AddToParagraph_BodyText_Text {
            get {
                return ResourceManager.GetString("Item_Format_ParagraphStructureLevels_AddToParagraph_BodyText_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level {0}.
        /// </summary>
        public static string Item_Format_ParagraphStructureLevels_AddToParagraph_Level_Text {
            get {
                return ResourceManager.GetString("Item_Format_ParagraphStructureLevels_AddToParagraph_Level_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Add to Paragraph.
        /// </summary>
        public static string Item_Format_ParagraphStructureLevels_AddToParagraph_Text {
            get {
                return ResourceManager.GetString("Item_Format_ParagraphStructureLevels_AddToParagraph_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Body Text.
        /// </summary>
        public static string Item_Format_ParagraphStructureLevels_CurrentParagraphStyle_BodyText_Text {
            get {
                return ResourceManager.GetString("Item_Format_ParagraphStructureLevels_CurrentParagraphStyle_BodyText_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level {0}.
        /// </summary>
        public static string Item_Format_ParagraphStructureLevels_CurrentParagraphStyle_Level_Text {
            get {
                return ResourceManager.GetString("Item_Format_ParagraphStructureLevels_CurrentParagraphStyle_Level_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Paragraph Style: {0}.
        /// </summary>
        public static string Item_Format_ParagraphStructureLevels_CurrentParagraphStyle_Text {
            get {
                return ResourceManager.GetString("Item_Format_ParagraphStructureLevels_CurrentParagraphStyle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paragraph Structure Le_vels.
        /// </summary>
        public static string Item_Format_ParagraphStructureLevels_Text {
            get {
                return ResourceManager.GetString("Item_Format_ParagraphStructureLevels_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sh_ape....
        /// </summary>
        public static string Item_Format_Shape_Text {
            get {
                return ResourceManager.GetString("Item_Format_Shape_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Styles....
        /// </summary>
        public static string Item_Format_Styles_Text {
            get {
                return ResourceManager.GetString("Item_Format_Styles_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabl_e of Contents....
        /// </summary>
        public static string Item_Format_TableOfContents_Text {
            get {
                return ResourceManager.GetString("Item_Format_TableOfContents_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Tabs....
        /// </summary>
        public static string Item_Format_Tabs_Text {
            get {
                return ResourceManager.GetString("Item_Format_Tabs_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F_ormat.
        /// </summary>
        public static string Item_Format_Text {
            get {
                return ResourceManager.GetString("Item_Format_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Te_xt Frame....
        /// </summary>
        public static string Item_Format_TextFrame_Text {
            get {
                return ResourceManager.GetString("Item_Format_TextFrame_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Barcode.
        /// </summary>
        public static string Item_Insert_Barcode_Text {
            get {
                return ResourceManager.GetString("Item_Insert_Barcode_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Delete....
        /// </summary>
        public static string Item_Insert_Bookmark_Delete_Text {
            get {
                return ResourceManager.GetString("Item_Insert_Bookmark_Delete_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Insert....
        /// </summary>
        public static string Item_Insert_Bookmark_Insert_Text {
            get {
                return ResourceManager.GetString("Item_Insert_Bookmark_Insert_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boo_kmark.
        /// </summary>
        public static string Item_Insert_Bookmark_Text {
            get {
                return ResourceManager.GetString("Item_Insert_Bookmark_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _More Columns....
        /// </summary>
        public static string Item_Insert_Columns_MoreColumns_Text {
            get {
                return ResourceManager.GetString("Item_Insert_Columns_MoreColumns_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _One.
        /// </summary>
        public static string Item_Insert_Columns_One_Text {
            get {
                return ResourceManager.GetString("Item_Insert_Columns_One_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Columns.
        /// </summary>
        public static string Item_Insert_Columns_Text {
            get {
                return ResourceManager.GetString("Item_Insert_Columns_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Two.
        /// </summary>
        public static string Item_Insert_Columns_Two_Text {
            get {
                return ResourceManager.GetString("Item_Insert_Columns_Two_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File....
        /// </summary>
        public static string Item_Insert_File_Text {
            get {
                return ResourceManager.GetString("Item_Insert_File_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Insert.
        /// </summary>
        public static string Item_Insert_Footer_Insert_Text {
            get {
                return ResourceManager.GetString("Item_Insert_Footer_Insert_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Remove.
        /// </summary>
        public static string Item_Insert_Footer_Remove_Text {
            get {
                return ResourceManager.GetString("Item_Insert_Footer_Remove_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F_ooter.
        /// </summary>
        public static string Item_Insert_Footer_Text {
            get {
                return ResourceManager.GetString("Item_Insert_Footer_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Check Box.
        /// </summary>
        public static string Item_Insert_FormField_CheckBox_Text {
            get {
                return ResourceManager.GetString("Item_Insert_FormField_CheckBox_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C_ombo Box.
        /// </summary>
        public static string Item_Insert_FormField_ComboBox_Text {
            get {
                return ResourceManager.GetString("Item_Insert_FormField_ComboBox_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D_ate Form Field.
        /// </summary>
        public static string Item_Insert_FormField_DateFormField_Text {
            get {
                return ResourceManager.GetString("Item_Insert_FormField_DateFormField_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D_elete.
        /// </summary>
        public static string Item_Insert_FormField_Delete_Text {
            get {
                return ResourceManager.GetString("Item_Insert_FormField_Delete_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Drop-Down List.
        /// </summary>
        public static string Item_Insert_FormField_DropDownList_Text {
            get {
                return ResourceManager.GetString("Item_Insert_FormField_DropDownList_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fo_rm Field.
        /// </summary>
        public static string Item_Insert_FormField_Text {
            get {
                return ResourceManager.GetString("Item_Insert_FormField_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Text Form Field.
        /// </summary>
        public static string Item_Insert_FormField_TextFormField_Text {
            get {
                return ResourceManager.GetString("Item_Insert_FormField_TextFormField_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Insert.
        /// </summary>
        public static string Item_Insert_Header_Insert_Text {
            get {
                return ResourceManager.GetString("Item_Insert_Header_Insert_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Remove.
        /// </summary>
        public static string Item_Insert_Header_Remove_Text {
            get {
                return ResourceManager.GetString("Item_Insert_Header_Remove_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Header.
        /// </summary>
        public static string Item_Insert_Header_Text {
            get {
                return ResourceManager.GetString("Item_Insert_Header_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyp_erlink....
        /// </summary>
        public static string Item_Insert_Hyperlink_Text {
            get {
                return ResourceManager.GetString("Item_Insert_Hyperlink_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Image....
        /// </summary>
        public static string Item_Insert_Image_Text {
            get {
                return ResourceManager.GetString("Item_Insert_Image_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Columns.
        /// </summary>
        public static string Item_Insert_PageBreaks_Column_Text {
            get {
                return ResourceManager.GetString("Item_Insert_PageBreaks_Column_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Page.
        /// </summary>
        public static string Item_Insert_PageBreaks_Page_Text {
            get {
                return ResourceManager.GetString("Item_Insert_PageBreaks_Page_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P_age Break.
        /// </summary>
        public static string Item_Insert_PageBreaks_Text {
            get {
                return ResourceManager.GetString("Item_Insert_PageBreaks_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Text Wrapping.
        /// </summary>
        public static string Item_Insert_PageBreaks_TextWrapping_Text {
            get {
                return ResourceManager.GetString("Item_Insert_PageBreaks_TextWrapping_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Delete.
        /// </summary>
        public static string Item_Insert_PageNumber_Delete_Text {
            get {
                return ResourceManager.GetString("Item_Insert_PageNumber_Delete_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Insert.
        /// </summary>
        public static string Item_Insert_PageNumber_Insert_Text {
            get {
                return ResourceManager.GetString("Item_Insert_PageNumber_Insert_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Page Number.
        /// </summary>
        public static string Item_Insert_PageNumber_Text {
            get {
                return ResourceManager.GetString("Item_Insert_PageNumber_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Continuous.
        /// </summary>
        public static string Item_Insert_SectionBreaks_Continuous_Text {
            get {
                return ResourceManager.GetString("Item_Insert_SectionBreaks_Continuous_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Next Page.
        /// </summary>
        public static string Item_Insert_SectionBreaks_NextPage_Text {
            get {
                return ResourceManager.GetString("Item_Insert_SectionBreaks_NextPage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sectio_n Break.
        /// </summary>
        public static string Item_Insert_SectionBreaks_Text {
            get {
                return ResourceManager.GetString("Item_Insert_SectionBreaks_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Basic Shapes.
        /// </summary>
        public static string Item_Insert_Shape_BasicShapes_Text {
            get {
                return ResourceManager.GetString("Item_Insert_Shape_BasicShapes_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block _Arrows.
        /// </summary>
        public static string Item_Insert_Shape_BlockArrows_Text {
            get {
                return ResourceManager.GetString("Item_Insert_Shape_BlockArrows_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Callouts.
        /// </summary>
        public static string Item_Insert_Shape_Callouts_Text {
            get {
                return ResourceManager.GetString("Item_Insert_Shape_Callouts_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Drawing Canvas.
        /// </summary>
        public static string Item_Insert_Shape_DrawingCanvas_Text {
            get {
                return ResourceManager.GetString("Item_Insert_Shape_DrawingCanvas_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Equation Shapes.
        /// </summary>
        public static string Item_Insert_Shape_EquationShapes_Text {
            get {
                return ResourceManager.GetString("Item_Insert_Shape_EquationShapes_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Flowchart.
        /// </summary>
        public static string Item_Insert_Shape_Flowchart_Text {
            get {
                return ResourceManager.GetString("Item_Insert_Shape_Flowchart_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Lines.
        /// </summary>
        public static string Item_Insert_Shape_Lines_Text {
            get {
                return ResourceManager.GetString("Item_Insert_Shape_Lines_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Rectangles.
        /// </summary>
        public static string Item_Insert_Shape_Rectangles_Text {
            get {
                return ResourceManager.GetString("Item_Insert_Shape_Rectangles_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Stars and Banners.
        /// </summary>
        public static string Item_Insert_Shape_StarsAndBanners_Text {
            get {
                return ResourceManager.GetString("Item_Insert_Shape_StarsAndBanners_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Shape.
        /// </summary>
        public static string Item_Insert_Shape_Text {
            get {
                return ResourceManager.GetString("Item_Insert_Shape_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sy_mbol....
        /// </summary>
        public static string Item_Insert_Symbol_Text {
            get {
                return ResourceManager.GetString("Item_Insert_Symbol_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Delete.
        /// </summary>
        public static string Item_Insert_TableOfContents_Delete_Text {
            get {
                return ResourceManager.GetString("Item_Insert_TableOfContents_Delete_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Insert.
        /// </summary>
        public static string Item_Insert_TableOfContents_Insert_Text {
            get {
                return ResourceManager.GetString("Item_Insert_TableOfContents_Insert_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab_le of Contents.
        /// </summary>
        public static string Item_Insert_TableOfContents_Text {
            get {
                return ResourceManager.GetString("Item_Insert_TableOfContents_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Update.
        /// </summary>
        public static string Item_Insert_TableOfContents_Update_Text {
            get {
                return ResourceManager.GetString("Item_Insert_TableOfContents_Update_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Insert.
        /// </summary>
        public static string Item_Insert_Text {
            get {
                return ResourceManager.GetString("Item_Insert_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Text Frame.
        /// </summary>
        public static string Item_Insert_TextFrame_Text {
            get {
                return ResourceManager.GetString("Item_Insert_TextFrame_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C_ells.
        /// </summary>
        public static string Item_Table_Delete_Cells_Text {
            get {
                return ResourceManager.GetString("Item_Table_Delete_Cells_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Columns.
        /// </summary>
        public static string Item_Table_Delete_Columns_Text {
            get {
                return ResourceManager.GetString("Item_Table_Delete_Columns_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Rows.
        /// </summary>
        public static string Item_Table_Delete_Rows_Text {
            get {
                return ResourceManager.GetString("Item_Table_Delete_Rows_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Table.
        /// </summary>
        public static string Item_Table_Delete_Table_Text {
            get {
                return ResourceManager.GetString("Item_Table_Delete_Table_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Delete.
        /// </summary>
        public static string Item_Table_Delete_Text {
            get {
                return ResourceManager.GetString("Item_Table_Delete_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _A1 Reference Style.
        /// </summary>
        public static string Item_Table_Formulas_A1ReferenceStyle_Text {
            get {
                return ResourceManager.GetString("Item_Table_Formulas_A1ReferenceStyle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Automatic _Calculation.
        /// </summary>
        public static string Item_Table_Formulas_AutomaticCalculation_Text {
            get {
                return ResourceManager.GetString("Item_Table_Formulas_AutomaticCalculation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit Formula....
        /// </summary>
        public static string Item_Table_Formulas_EditFormula_Text {
            get {
                return ResourceManager.GetString("Item_Table_Formulas_EditFormula_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _R1C1 Reference Style.
        /// </summary>
        public static string Item_Table_Formulas_R1C1ReferenceStyle_Text {
            get {
                return ResourceManager.GetString("Item_Table_Formulas_R1C1ReferenceStyle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Formulas.
        /// </summary>
        public static string Item_Table_Formulas_Text {
            get {
                return ResourceManager.GetString("Item_Table_Formulas_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column To The _Left.
        /// </summary>
        public static string Item_Table_Insert_ColumnToTheLeft_Text {
            get {
                return ResourceManager.GetString("Item_Table_Insert_ColumnToTheLeft_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column To The _Right.
        /// </summary>
        public static string Item_Table_Insert_ColumnToTheRight_Text {
            get {
                return ResourceManager.GetString("Item_Table_Insert_ColumnToTheRight_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row _Above.
        /// </summary>
        public static string Item_Table_Insert_RowAbove_Text {
            get {
                return ResourceManager.GetString("Item_Table_Insert_RowAbove_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row _Below.
        /// </summary>
        public static string Item_Table_Insert_RowBelow_Text {
            get {
                return ResourceManager.GetString("Item_Table_Insert_RowBelow_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Table....
        /// </summary>
        public static string Item_Table_Insert_Table_Text {
            get {
                return ResourceManager.GetString("Item_Table_Insert_Table_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Insert.
        /// </summary>
        public static string Item_Table_Insert_Text {
            get {
                return ResourceManager.GetString("Item_Table_Insert_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Merge Cells.
        /// </summary>
        public static string Item_Table_MergeCells_Text {
            get {
                return ResourceManager.GetString("Item_Table_MergeCells_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Properties....
        /// </summary>
        public static string Item_Table_Properties_Text {
            get {
                return ResourceManager.GetString("Item_Table_Properties_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C_ell.
        /// </summary>
        public static string Item_Table_Select_Cell_Text {
            get {
                return ResourceManager.GetString("Item_Table_Select_Cell_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Column.
        /// </summary>
        public static string Item_Table_Select_Column_Text {
            get {
                return ResourceManager.GetString("Item_Table_Select_Column_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Row.
        /// </summary>
        public static string Item_Table_Select_Row_Text {
            get {
                return ResourceManager.GetString("Item_Table_Select_Row_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Table.
        /// </summary>
        public static string Item_Table_Select_Table_Text {
            get {
                return ResourceManager.GetString("Item_Table_Select_Table_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Select.
        /// </summary>
        public static string Item_Table_Select_Text {
            get {
                return ResourceManager.GetString("Item_Table_Select_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split _Cells.
        /// </summary>
        public static string Item_Table_SplitCells_Text {
            get {
                return ResourceManager.GetString("Item_Table_SplitCells_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Above.
        /// </summary>
        public static string Item_Table_SplitTable_Above_Text {
            get {
                return ResourceManager.GetString("Item_Table_SplitTable_Above_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Below.
        /// </summary>
        public static string Item_Table_SplitTable_Below_Text {
            get {
                return ResourceManager.GetString("Item_Table_SplitTable_Below_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split _Table.
        /// </summary>
        public static string Item_Table_SplitTable_Text {
            get {
                return ResourceManager.GetString("Item_Table_SplitTable_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Table.
        /// </summary>
        public static string Item_Table_Text {
            get {
                return ResourceManager.GetString("Item_Table_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B_ookmark Markers.
        /// </summary>
        public static string Item_View_BookmarkMarkers_Text {
            get {
                return ResourceManager.GetString("Item_View_BookmarkMarkers_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Button Bar.
        /// </summary>
        public static string Item_View_ButtonBar_Text {
            get {
                return ResourceManager.GetString("Item_View_ButtonBar_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Always.
        /// </summary>
        public static string Item_View_Comments_Always_Text {
            get {
                return ResourceManager.GetString("Item_View_Comments_Always_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Current.
        /// </summary>
        public static string Item_View_Comments_Current_Text {
            get {
                return ResourceManager.GetString("Item_View_Comments_Current_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Never.
        /// </summary>
        public static string Item_View_Comments_Never_Text {
            get {
                return ResourceManager.GetString("Item_View_Comments_Never_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Co_mments.
        /// </summary>
        public static string Item_View_Comments_Text {
            get {
                return ResourceManager.GetString("Item_View_Comments_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Control Chars.
        /// </summary>
        public static string Item_View_ControlChars_Text {
            get {
                return ResourceManager.GetString("Item_View_ControlChars_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Draft.
        /// </summary>
        public static string Item_View_Draft_Text {
            get {
                return ResourceManager.GetString("Item_View_Draft_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dra_wing Marker Lines.
        /// </summary>
        public static string Item_View_DrawingMarkerLines_Text {
            get {
                return ResourceManager.GetString("Item_View_DrawingMarkerLines_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Always.
        /// </summary>
        public static string Item_View_EditableRegions_Always_Text {
            get {
                return ResourceManager.GetString("Item_View_EditableRegions_Always_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Current.
        /// </summary>
        public static string Item_View_EditableRegions_Current_Text {
            get {
                return ResourceManager.GetString("Item_View_EditableRegions_Current_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Never.
        /// </summary>
        public static string Item_View_EditableRegions_Never_Text {
            get {
                return ResourceManager.GetString("Item_View_EditableRegions_Never_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Editiable Regions.
        /// </summary>
        public static string Item_View_EditableRegions_Text {
            get {
                return ResourceManager.GetString("Item_View_EditableRegions_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Horizontal Ruler.
        /// </summary>
        public static string Item_View_HorizontalRuler_Text {
            get {
                return ResourceManager.GetString("Item_View_HorizontalRuler_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Page Layout.
        /// </summary>
        public static string Item_View_PageLayout_Text {
            get {
                return ResourceManager.GetString("Item_View_PageLayout_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Right to Left Layout.
        /// </summary>
        public static string Item_View_RightToLeftLayout_Text {
            get {
                return ResourceManager.GetString("Item_View_RightToLeftLayout_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Status Bar.
        /// </summary>
        public static string Item_View_StatusBar_Text {
            get {
                return ResourceManager.GetString("Item_View_StatusBar_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Table Gridlines.
        /// </summary>
        public static string Item_View_TableGridlines_Text {
            get {
                return ResourceManager.GetString("Item_View_TableGridlines_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _View.
        /// </summary>
        public static string Item_View_Text {
            get {
                return ResourceManager.GetString("Item_View_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text _Frame Marker Lines.
        /// </summary>
        public static string Item_View_TextFrameMarkerLines_Text {
            get {
                return ResourceManager.GetString("Item_View_TextFrameMarkerLines_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tr_acked Changes.
        /// </summary>
        public static string Item_View_TrackedChanges_Text {
            get {
                return ResourceManager.GetString("Item_View_TrackedChanges_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Vertical Ruler.
        /// </summary>
        public static string Item_View_VerticalRuler_Text {
            get {
                return ResourceManager.GetString("Item_View_VerticalRuler_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}%.
        /// </summary>
        public static string Item_View_Zoom_Factor_Text {
            get {
                return ResourceManager.GetString("Item_View_Zoom_Factor_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Zoom.
        /// </summary>
        public static string Item_View_Zoom_Text {
            get {
                return ResourceManager.GetString("Item_View_Zoom_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TX Text Control Words.
        /// </summary>
        public static string MainWindow_Caption_Product {
            get {
                return ResourceManager.GetString("MainWindow_Caption_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [untitled].
        /// </summary>
        public static string MainWindow_Caption_Untitled {
            get {
                return ResourceManager.GetString("MainWindow_Caption_Untitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Comment.
        /// </summary>
        public static string MessageBox_AddComment_Error_Caption {
            get {
                return ResourceManager.GetString("MessageBox_AddComment_Error_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occurred..
        /// </summary>
        public static string MessageBox_AddComment_Error_Text {
            get {
                return ResourceManager.GetString("MessageBox_AddComment_Error_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Comment.
        /// </summary>
        public static string MessageBox_AddComment_NoSelection_Caption {
            get {
                return ResourceManager.GetString("MessageBox_AddComment_NoSelection_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First select a part of the document to add a comment about it..
        /// </summary>
        public static string MessageBox_AddComment_NoSelection_Text {
            get {
                return ResourceManager.GetString("MessageBox_AddComment_NoSelection_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Comment.
        /// </summary>
        public static string MessageBox_AddComment_PositionInvalid_Caption {
            get {
                return ResourceManager.GetString("MessageBox_AddComment_PositionInvalid_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The comment wasn&apos;t inserted because the specified position values (start and/or length) are invalid..
        /// </summary>
        public static string MessageBox_AddComment_PositionInvalid_Text {
            get {
                return ResourceManager.GetString("MessageBox_AddComment_PositionInvalid_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Comment.
        /// </summary>
        public static string MessageBox_AddComment_SelectionTooComplex_Caption {
            get {
                return ResourceManager.GetString("MessageBox_AddComment_SelectionTooComplex_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The comment wasn&apos;t inserted because the selection is too complex. It is not a continuous sequence of characters..
        /// </summary>
        public static string MessageBox_AddComment_SelectionTooComplex_Text {
            get {
                return ResourceManager.GetString("MessageBox_AddComment_SelectionTooComplex_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editable Regions.
        /// </summary>
        public static string MessageBox_AddEditableRegion_Error_Caption {
            get {
                return ResourceManager.GetString("MessageBox_AddEditableRegion_Error_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occurred..
        /// </summary>
        public static string MessageBox_AddEditableRegion_Error_Text {
            get {
                return ResourceManager.GetString("MessageBox_AddEditableRegion_Error_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editable Regions.
        /// </summary>
        public static string MessageBox_AddEditableRegion_NoSelection_Caption {
            get {
                return ResourceManager.GetString("MessageBox_AddEditableRegion_NoSelection_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First select a part of the document and then choose the user who can freely edit it..
        /// </summary>
        public static string MessageBox_AddEditableRegion_NoSelection_Text {
            get {
                return ResourceManager.GetString("MessageBox_AddEditableRegion_NoSelection_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editable Regions.
        /// </summary>
        public static string MessageBox_AddEditableRegion_PositionInvalid_Caption {
            get {
                return ResourceManager.GetString("MessageBox_AddEditableRegion_PositionInvalid_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The editable region wasn&apos;t inserted because the specified position values (start and/or length) are invalid..
        /// </summary>
        public static string MessageBox_AddEditableRegion_PositionInvalid_Text {
            get {
                return ResourceManager.GetString("MessageBox_AddEditableRegion_PositionInvalid_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editable Regions.
        /// </summary>
        public static string MessageBox_AddEditableRegion_SelectionTooComplex_Caption {
            get {
                return ResourceManager.GetString("MessageBox_AddEditableRegion_SelectionTooComplex_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The editable region wasn&apos;t inserted because the selection is too complex. It is not a continuous sequence of characters..
        /// </summary>
        public static string MessageBox_AddEditableRegion_SelectionTooComplex_Text {
            get {
                return ResourceManager.GetString("MessageBox_AddEditableRegion_SelectionTooComplex_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following exception is thrown:
        ///	
        ///&quot;{0}&quot;
        ///
        ///To get help, please visit the Text Control Support at www.textcontrol.com..
        /// </summary>
        public static string MessageBox_Application_ThreadException_Text {
            get {
                return ResourceManager.GetString("MessageBox_Application_ThreadException_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Form Layout.
        /// </summary>
        public static string MessageBox_ChangeFormLayout_Caption {
            get {
                return ResourceManager.GetString("MessageBox_ChangeFormLayout_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To change the program&apos;s view to a {0} to {1} text appearance, the application must be restarted. 
        ///Click OK to restart or Cancel to not restart the program..
        /// </summary>
        public static string MessageBox_ChangeFormLayout_Text {
            get {
                return ResourceManager.GetString("MessageBox_ChangeFormLayout_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Hyperlink.
        /// </summary>
        public static string MessageBox_OpenHyperlink_CouldNotOpenLink_Caption {
            get {
                return ResourceManager.GetString("MessageBox_OpenHyperlink_CouldNotOpenLink_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open link to &apos;{0}&apos;..
        /// </summary>
        public static string MessageBox_OpenHyperlink_CouldNotOpenLink_Text {
            get {
                return ResourceManager.GetString("MessageBox_OpenHyperlink_CouldNotOpenLink_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open linked File.
        /// </summary>
        public static string MessageBox_OpenHyperlink_FileDoesNotExist_Caption {
            get {
                return ResourceManager.GetString("MessageBox_OpenHyperlink_FileDoesNotExist_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The linked file &apos;{0}&apos; does not exist..
        /// </summary>
        public static string MessageBox_OpenHyperlink_FileDoesNotExist_Text {
            get {
                return ResourceManager.GetString("MessageBox_OpenHyperlink_FileDoesNotExist_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Recent File.
        /// </summary>
        public static string MessageBox_OpenRecentFile_FileDoesNotExist_Caption {
            get {
                return ResourceManager.GetString("MessageBox_OpenRecentFile_FileDoesNotExist_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected file does not exist. Do you want to remove it from the list of recent files?.
        /// </summary>
        public static string MessageBox_OpenRecentFile_FileDoesNotExist_Text {
            get {
                return ResourceManager.GetString("MessageBox_OpenRecentFile_FileDoesNotExist_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Password.
        /// </summary>
        public static string MessageBox_PasswordDialog_IncorrectPassword_Caption {
            get {
                return ResourceManager.GetString("MessageBox_PasswordDialog_IncorrectPassword_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered password is incorrect..
        /// </summary>
        public static string MessageBox_PasswordDialog_IncorrectPassword_Text {
            get {
                return ResourceManager.GetString("MessageBox_PasswordDialog_IncorrectPassword_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left.
        /// </summary>
        public static string MessageBox_SaveDirtyDocumentBeforeRestart_Left {
            get {
                return ResourceManager.GetString("MessageBox_SaveDirtyDocumentBeforeRestart_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to right.
        /// </summary>
        public static string MessageBox_SaveDirtyDocumentBeforeRestart_Right {
            get {
                return ResourceManager.GetString("MessageBox_SaveDirtyDocumentBeforeRestart_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To change the program&apos;s view to a {0} to {1} text appearance, the application must be restarted. Also, changes to &apos;{2}&apos; were not saved.
        ///Click Yes to save these changes and restart, No to restart without saving, or Cancel to not restart..
        /// </summary>
        public static string MessageBox_SaveDirtyDocumentBeforeRestart_ToFile {
            get {
                return ResourceManager.GetString("MessageBox_SaveDirtyDocumentBeforeRestart_ToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To change the program&apos;s view to a {0} to {1} text appearance, the application must be restarted. Also, changes to the document were not saved.
        ///Click Yes to save these changes and restart, No to restart without saving, or Cancel to not restart..
        /// </summary>
        public static string MessageBox_SaveDirtyDocumentBeforeRestart_Untitled {
            get {
                return ResourceManager.GetString("MessageBox_SaveDirtyDocumentBeforeRestart_Untitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MessageBox_SaveDirtyDocumentOnExit_Caption {
            get {
                return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnExit_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save changes to &apos;{0}&apos; before the program closes? 
        ///Click Yes to save and close, No to close without saving, or Cancel to not close..
        /// </summary>
        public static string MessageBox_SaveDirtyDocumentOnExit_ToFile {
            get {
                return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnExit_ToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the document before the program closes? 
        ///Click Yes to save and close, No to close without saving, or Cancel to not close..
        /// </summary>
        public static string MessageBox_SaveDirtyDocumentOnExit_Untitled {
            get {
                return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnExit_Untitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string MessageBox_SaveDirtyDocumentOnNew_Caption {
            get {
                return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnNew_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save changes to &apos;{0}&apos; before a new document is created? 
        ///Click Yes to save and create, No to create without saving, or Cancel to not to create a new document..
        /// </summary>
        public static string MessageBox_SaveDirtyDocumentOnNew_ToFile {
            get {
                return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnNew_ToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the document before a new document is created? 
        ///Click Yes to save and create, No to create without saving, or Cancel to not to create a new document..
        /// </summary>
        public static string MessageBox_SaveDirtyDocumentOnNew_Untitled {
            get {
                return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnNew_Untitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string MessageBox_SaveDirtyDocumentOnOpen_Caption {
            get {
                return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnOpen_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save changes to &apos;{0}&apos; before the new document is opened? 
        ///Click Yes to save and open, No to open without saving, or Cancel to not to open the new document..
        /// </summary>
        public static string MessageBox_SaveDirtyDocumentOnOpen_ToFile {
            get {
                return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnOpen_ToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the document before the new document is opened? 
        ///Click Yes to save and open, No to open without saving, or Cancel to not to open the new document..
        /// </summary>
        public static string MessageBox_SaveDirtyDocumentOnOpen_Untitled {
            get {
                return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnOpen_Untitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Of Contents.
        /// </summary>
        public static string MessageBox_UpdateTableOfContents_NoContents_Caption {
            get {
                return ResourceManager.GetString("MessageBox_UpdateTableOfContents_NoContents_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No table of contents entries found..
        /// </summary>
        public static string MessageBox_UpdateTableOfContents_NoContents_Text {
            get {
                return ResourceManager.GetString("MessageBox_UpdateTableOfContents_NoContents_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string MessageBox_UserAccess_SignOut_Caption {
            get {
                return ResourceManager.GetString("MessageBox_UserAccess_SignOut_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was successfully signed out..
        /// </summary>
        public static string MessageBox_UserAccess_SignOut_Text {
            get {
                return ResourceManager.GetString("MessageBox_UserAccess_SignOut_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By deleting the account, the current user will be signed out. Click OK to proceed or Cancel to not delete the account..
        /// </summary>
        public static string MessageBox_UserAccessDialogDeleteAccount_Text {
            get {
                return ResourceManager.GetString("MessageBox_UserAccessDialogDeleteAccount_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered password does not match the given user&apos;s password..
        /// </summary>
        public static string MessageBox_UserAccessDialogIncorrectPassword_Text {
            get {
                return ResourceManager.GetString("MessageBox_UserAccessDialogIncorrectPassword_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Tracked Changes.
        /// </summary>
        public static string Method_SetTrackedChangesHighlightMode_HideTrackedChanges {
            get {
                return ResourceManager.GetString("Method_SetTrackedChangesHighlightMode_HideTrackedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight Tracked Changes.
        /// </summary>
        public static string Method_SetTrackedChangesHighlightMode_HighlightTrackedChanges {
            get {
                return ResourceManager.GetString("Method_SetTrackedChangesHighlightMode_HighlightTrackedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string PasswordDialog_Cancel {
            get {
                return ResourceManager.GetString("PasswordDialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordDialog_Caption {
            get {
                return ResourceManager.GetString("PasswordDialog_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a password to open the document..
        /// </summary>
        public static string PasswordDialog_EnterPassword {
            get {
                return ResourceManager.GetString("PasswordDialog_EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string PasswordDialog_OK {
            get {
                return ResourceManager.GetString("PasswordDialog_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Password:.
        /// </summary>
        public static string PasswordDialog_Password {
            get {
                return ResourceManager.GetString("PasswordDialog_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document &apos;{0}&apos; is protected..
        /// </summary>
        public static string PasswordDialog_ProtectedDocument {
            get {
                return ResourceManager.GetString("PasswordDialog_ProtectedDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column: .
        /// </summary>
        public static string StatusBar_Column {
            get {
                return ResourceManager.GetString("StatusBar_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line: .
        /// </summary>
        public static string StatusBar_Line {
            get {
                return ResourceManager.GetString("StatusBar_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page: .
        /// </summary>
        public static string StatusBar_Page {
            get {
                return ResourceManager.GetString("StatusBar_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section: .
        /// </summary>
        public static string StatusBar_Section {
            get {
                return ResourceManager.GetString("StatusBar_Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Settings.
        /// </summary>
        public static string UserAccessDialog_AccountSettings_Caption {
            get {
                return ResourceManager.GetString("UserAccessDialog_AccountSettings_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Confirm Password:.
        /// </summary>
        public static string UserAccessDialog_AccountSettings_ConfirmPassword {
            get {
                return ResourceManager.GetString("UserAccessDialog_AccountSettings_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Delete Account.
        /// </summary>
        public static string UserAccessDialog_AccountSettings_Delete {
            get {
                return ResourceManager.GetString("UserAccessDialog_AccountSettings_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New Password:.
        /// </summary>
        public static string UserAccessDialog_AccountSettings_NewPassword {
            get {
                return ResourceManager.GetString("UserAccessDialog_AccountSettings_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Old Password:.
        /// </summary>
        public static string UserAccessDialog_AccountSettings_OldPassword {
            get {
                return ResourceManager.GetString("UserAccessDialog_AccountSettings_OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string UserAccessDialog_Cancel {
            get {
                return ResourceManager.GetString("UserAccessDialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New User Account.
        /// </summary>
        public static string UserAccessDialog_CreateAccount_Caption {
            get {
                return ResourceManager.GetString("UserAccessDialog_CreateAccount_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Confirm Password:.
        /// </summary>
        public static string UserAccessDialog_CreateAccount_ConfirmPassword {
            get {
                return ResourceManager.GetString("UserAccessDialog_CreateAccount_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New Password:.
        /// </summary>
        public static string UserAccessDialog_CreateAccount_NewPassword {
            get {
                return ResourceManager.GetString("UserAccessDialog_CreateAccount_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string UserAccessDialog_OK {
            get {
                return ResourceManager.GetString("UserAccessDialog_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string UserAccessDialog_SignIn_Caption {
            get {
                return ResourceManager.GetString("UserAccessDialog_SignIn_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Password:.
        /// </summary>
        public static string UserAccessDialog_SignIn_Password {
            get {
                return ResourceManager.GetString("UserAccessDialog_SignIn_Password", resourceCulture);
            }
        }
    }
}
